server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://134.0.133.66:3306/boc_strategy?autoReconnect:true&useUnicode:true&characterEncoding:UTF-8&serverTimezone:GMT%2B8
    username: bocenter
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: DatebookHikariCP
      connection-test-query: SELECT 1 FROM DUAL
      auto-commit: true
  redis:
    host: 134.0.133.66
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 1
        max-wait: 10ms
        max-idle: 8


  influx:
    url: http://192.168.240.128:8086
    userName: root
    password: root
    database: performance
    retention_policy: default
    retention_policy_time: 30d

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.bread.coalquality.mvc.entity
  global-config:
    id-type: 2
    field-strategy: 0
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
